### ISSUE TITLE
Zoom - 09.05

### ISSUE THREAD

**Issue by GorudoYami** [GorudoYami/SensorDataCollector#10]
Join Zoom Meeting
[https://us05web.zoom.us/j/84258247591?pwd=lcT4otb0VKN0N8NouWhy31LiKEitMT.1](https://www.google.com/url?q=https://us05web.zoom.us/j/84258247591?pwd%3DlcT4otb0VKN0N8NouWhy31LiKEitMT.1&sa=D&source=calendar&ust=1713102361970806&usg=AOvVaw3281N4kLWV6y8v4tjL2iUd)

Meeting ID: 842 5824 7591
Passcode: 3jxzsh

**Comment by GorudoYami** [comment]
Join Zoom Meeting
[https://us05web.zoom.us/j/84258247591?pwd=lcT4otb0VKN0N8NouWhy31LiKEitMT.1](https://www.google.com/url?q=https://us05web.zoom.us/j/84258247591?pwd%3DlcT4otb0VKN0N8NouWhy31LiKEitMT.1&sa=D&source=calendar&ust=1713102361970806&usg=AOvVaw3281N4kLWV6y8v4tjL2iUd)

Meeting ID: 842 5824 7591
Passcode: 3jxzsh

**Comment by GorudoYami** [comment]
Do meeta trzeba zrobic #1 #9 #6 #5

**Comment by opavliuk1980** [comment]
video from Zoom

https://polslpl-my.sharepoint.com/:f:/g/personal/opavliuk_polsl_pl/EuqsYtoWZA1Fo4arpbjAgCsB3zZPihwOvk6XU3PHXUEz3g?e=ImYBJd
